Repository RAF-SI-2023/Banka-3-Frontend, pull requests merged in 2024-06, with the labels that each got.

#161 Add helm deployment
  .prow/build.yaml
Labels: size/XS

#162 izbrisan test
  cypress/e2e/transaction.cy.ts
Labels: size/M, approved, lgtm

#158 Profit table komponenta i gard za nasu banku
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/profit-table/mock-profits.ts
  src/app/compnents/profit-table/profit-table.component.css
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.spec.ts
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/guards/our-company.guard.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: size/L, approved, lgtm

#164 Add prod build config
  .prow/build.yaml
  angular.json
  package.json
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
Labels: size/M

#166 Push separate image for dev and prod
  .prow/build.yaml
Labels: size/S

#169 Update from master
  .prow/build.yaml
  angular.json
  package.json
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
Labels: size/M, approved, lgtm

#171 Update dev
  .prow/build.yaml
Labels: size/S

#172 Sprint 9
  cypress/e2e/transaction.cy.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/profit-table/mock-profits.ts
  src/app/compnents/profit-table/profit-table.component.css
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.spec.ts
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/guards/our-company.guard.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: size/L, approved, lgtm

#175 Update build.yaml
  .prow/build.yaml
Labels: size/S

#176 Ispravke ogisa za sprint-9
  src/app/app-routing.module.ts
  src/app/compnents/home-page/home-page.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.ts
  src/app/compnents/transaction_components/paying/paying.component.html
  src/app/compnents/transaction_components/paying/paying.component.ts
  src/app/compnents/transaction_components/transaction-details/transaction-details.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/websocket.service.ts
Labels: size/L, approved, lgtm

#179 KT5 ispravke i dodaci
  cypress/e2e/create-user.cy.ts
  src/app/compnents/listing_components/buy-forex-popup/buy-forex-popup.component.html
  src/app/compnents/listing_components/buy-forex-popup/buy-forex-popup.component.ts
  src/app/compnents/listing_components/buy-option-popup/buy-option-popup.component.html
  src/app/compnents/listing_components/buy-option-popup/buy-option-popup.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.css
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/options/options.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.ts
  src/app/compnents/password_components/password-activation/password-activation.component.ts
  src/app/compnents/password_components/reset-password/password-confirmation/password-confirmation.component.ts
  src/app/compnents/profit-table/profit-table.component.css
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/websocket.service.ts
Labels: size/L, approved, lgtm

#180 Kt 5 ogisa izmene
  README.md
Labels: approved, lgtm

#181 Update build.yaml
  .prow/build.yaml
Labels: approved, size/XS, lgtm

#187 Izmena gresaka i brisanje testova (privremeno)
  cypress/e2e/admin-login.cy.ts
  cypress/e2e/create-employee.cy.ts
  cypress/e2e/user-login.cy.ts
  package-lock.json
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/services/exchange.service.ts
Labels: size/L, approved, lgtm

#188 Add videos debug and change path
  .prow/frontend.yaml
Labels: approved, size/XS, lgtm

#189 Ci/echo cy results
  .prow/frontend.yaml
  cypress.config.ts
Labels: size/S, approved, lgtm

#191 FRN-46
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.css
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.html
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.spec.ts
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/models/models.ts
  src/app/services/account.service.ts
Labels: size/XL, approved, lgtm

#190 FRN-47 Kreiranje marznog racuna user/firma
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.css
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.html
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.css
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.html
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.ts
  src/app/models/models.ts
  src/app/services/account.service.ts
Labels: size/L, ok-to-test, approved, lgtm

#192 Listing komponente i options promene izgleda
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.css
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/options/options.component.css
  src/app/compnents/listing_components/options/options.component.html
  src/app/compnents/listing_components/options/options.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/otc/bank-otc/bank-otc.component.css
  src/app/compnents/otc/bank-otc/bank-otc.component.html
  src/app/compnents/otc/bank-otc/bank-otc.component.spec.ts
  src/app/compnents/otc/bank-otc/bank-otc.component.ts
  src/app/compnents/otc/otc-banka4-buy-popup/otc-banka4-buy-popup.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/websocket.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/L, approved, lgtm

#193 promena web socketa
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.css
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.html
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.html
  src/app/compnents/otc/otc-view/otc-view.component.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
Labels: size/M, approved, lgtm

#194 my margin stocks uradjeni
  src/app/compnents/listing_components/buy-hartije/buy-hartije.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.css
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/websocket.service.ts
Labels: size/L, approved, lgtm

#196 Fix ci docker command
  .prow/frontend.yaml
Labels: approved, size/XS, lgtm

#195 uradjeni za ispit greske
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.css
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.html
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/login/company-login/company-login.component.html
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.css
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.html
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/otc/bank-otc/bank-otc.component.html
  src/app/compnents/otc/bank-otc/bank-otc.component.ts
  src/app/models/models.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: size/L, approved, lgtm

#197 sitne izmene za profit
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.html
  src/app/compnents/company-home-page/company-home-page.component.html
  src/app/compnents/home-page/home-page.component.html
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.ts
  src/app/compnents/profit-table/profit-table.component.css
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/compnents/transaction_components/paying/paying.component.ts
  src/app/models/models.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: approved, lgtm
