Repository RAF-SI-2023/Banka-3-Frontend, pull requests merged in 2024-04, with the labels that each got.

#81 Izgled komponente za prikaz liste zahteva za kupovanje hartija.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/models/models.ts
Labels: size/L

#84 Dodat stock details ekran
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/chart/chart.component.css
  src/app/chart/chart.component.html
  src/app/chart/chart.component.spec.ts
  src/app/chart/chart.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/stock-info/stock-info.component.css
  src/app/stock-info/stock-info.component.html
  src/app/stock-info/stock-info.component.spec.ts
  src/app/stock-info/stock-info.component.ts
Labels: size/L

#85 Options Komponenta
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/options/options.component.css
  src/app/options/options.component.html
  src/app/options/options.component.spec.ts
  src/app/options/options.component.ts
Labels: size/L

#86 Obrada podataka za prikaz na dijagramu
  src/app/app-routing.module.ts
  src/app/chart/chart.component.ts
  src/app/services/exchange.service.ts
  src/app/stock-info/mock-data.ts
  src/app/stock-info/stock-info.component.html
  src/app/stock-info/stock-info.component.ts
Labels: size/XL

#87 Uskladjivanje podataka za prikaz Stock-a
  src/app/services/exchange.service.ts
  src/app/stock-info/stock-info.component.css
  src/app/stock-info/stock-info.component.html
  src/app/stock-info/stock-info.component.ts
Labels: size/L

#88 FRN 26
  src/app/app-routing.module.ts
  src/app/credit-list-user/credit-list-user.component.html
  src/app/options/options.component.css
  src/app/options/options.component.html
  src/app/options/options.component.ts
  src/app/services/exchange.service.ts
Labels: size/L

#89 Odradjena Supervisor lista, dodat model za zahteve i mock podataka.
  src/app/hartije/supervisor-listsing-list/mock-requests.ts
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/assets/circle-check-svgrepo-com.svg
  src/assets/circle-quarters-svgrepo-com.svg
Labels: size/L

#97 FRN-34
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/card-view/card-view.component.css
  src/app/card-view/card-view.component.html
  src/app/card-view/card-view.component.spec.ts
  src/app/card-view/card-view.component.ts
  src/app/card-view/date-pipe/formatdate.pipe.spec.ts
  src/app/card-view/date-pipe/formatdate.pipe.ts
  src/app/card-view/mock-cards.ts
  src/app/models/models.ts
  src/app/navbar/navbar.component.html
  src/app/services/card.service.spec.ts
  src/app/services/card.service.ts
  src/assets/credit-card-payment-round-svgrepo-com(1).svg
  src/assets/mastercard-logo.svg
  src/assets/visa-blue-card-logo.svg
  src/assets/visa-card-logo.svg
Labels: size/L

#98 dodata 2 guarda, fiksan mail, redirekcija supervisora, hartije u navbaru
  src/app/app-routing.module.ts
  src/app/guards/agent.guard.ts
  src/app/guards/supervisor.guard.ts
  src/app/login/userlogin/userlogin.component.css
  src/app/login/userlogin/userlogin.component.html
  src/app/login/userlogin/userlogin.component.ts
  src/app/navbar/navbar.component.html
  src/app/services/user.service.ts
Labels: size/L

#99 FRN 33
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/bankomat-view-card/bankomat-view-card.component.css
  src/app/bankomat-view-card/bankomat-view-card.component.html
  src/app/bankomat-view-card/bankomat-view-card.component.spec.ts
  src/app/bankomat-view-card/bankomat-view-card.component.ts
  src/app/bankomat-view/bankomat-view.component.css
  src/app/bankomat-view/bankomat-view.component.html
  src/app/bankomat-view/bankomat-view.component.spec.ts
  src/app/bankomat-view/bankomat-view.component.ts
  src/app/services/card.service.ts
Labels: size/XL

#100 FRN-32
  src/app/buy-hartije-popup/buy-hartije-popup.component.css
  src/app/buy-hartije-popup/buy-hartije-popup.component.html
  src/app/buy-hartije-popup/buy-hartije-popup.component.ts
  src/app/buy-hartije/buy-hartije.component.css
  src/app/buy-hartije/buy-hartije.component.html
  src/app/buy-hartije/buy-hartije.component.ts
  src/app/services/exchange.service.ts
Labels: size/L

#101 Increase production budget limit
  angular.json
Labels: size/XS

#102 dodati racuni u payment komponentu, redirekcija na options/:ticker
  src/app/hartije/listing-list/listing-list.component.ts
  src/app/paying/paying.component.html
  src/app/paying/paying.component.ts
  src/app/services/account.service.ts
Labels: size/M

#103 pozvne u supervisor-list hartije, dodati limiti, forex i futures prikaz
  src/app/app-routing.module.ts
  src/app/hartije/listing-list/listing-list.component.html
  src/app/hartije/listing-list/listing-list.component.ts
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
Labels: size/L

#105 Cypress
  package-lock.json
  package.json
Labels: size/XXL

#106 Create nginx.conf
  nginx.conf
Labels: size/S

#108 Ispravka login componente
  src/app/login/userlogin/userlogin.component.ts
Labels: size/S

#109 Supervisor listing ispravke
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/hartije/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
Labels: size/L

#110 uradjeni e2e testovi za login user, login employee, add user i add em…
  cypress/e2e/admin-login.cy.ts
  cypress/e2e/create-employee.cy.ts
  cypress/e2e/create-user.cy.ts
  cypress/e2e/main.cy.ts
  cypress/e2e/user-login.cy.ts
  src/app/create-employee/create-employee.component.ts
Labels: size/L

#111 Placanje ispravke
  src/app/create-payment-recipient/create-payment-recipient.component.html
  src/app/create-payment-recipient/create-payment-recipient.component.ts
  src/app/edit-payment-recipient/edit-payment-recipient.component.ts
  src/app/models/models.ts
  src/app/paying/paying.component.css
  src/app/paying/paying.component.html
  src/app/paying/paying.component.ts
  src/app/payment-recipient/mock-recipients.ts
  src/app/payment-recipient/payment-recipient.component.html
  src/app/payment-recipient/payment-recipient.component.ts
  src/app/services/user.service.ts
Labels: size/L

#113 Ispravke gresaka i povezivanje sa backom
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/employee_components/user-controll/user-controll.component.html
  src/app/compnents/employee_components/user-controll/user-controll.component.ts
  src/app/compnents/firm_components/firm-add-account-form/firm-add-account-form.component.ts
  src/app/compnents/home-page/home-page.component.css
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/sell-future-popup/buy-future-popup.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/compnents/navbar/navbar.component.css
  src/app/compnents/navbar/navbar.component.html
  src/app/models/models.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: size/M, approved, lgtm

#112 Prow init
  .prow/build.yaml
  .prow/frontend.yaml
  cypress/e2e/admin-login.cy.ts
  cypress/e2e/create-employee.cy.ts
  cypress/e2e/create-user.cy.ts
  cypress/e2e/user-login.cy.ts
Labels: size/L, approved, lgtm

#116 Cd fixes
  .prow/build.yaml
  OWNERS
Labels: size/S, approved, lgtm

#115 Dodat test za transakcije
  cypress/e2e/transaction.cy.ts
  cypress/e2e/user-login.cy.ts
Labels: size/M, approved, lgtm

#117 CD - Fix frontend build context
  .prow/build.yaml
Labels: approved, size/XS, lgtm

#118 Ispravljanje sitnih gresaka
  src/app/compnents/credit_components/credit-list/credit-list.component.html
  src/app/compnents/credit_components/credit-transaction/credit-transaction.component.ts
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/login/admin-login/admin-login.component.ts
  src/app/compnents/login/company-login/company-login.component.ts
  src/app/compnents/login/userlogin/userlogin.component.ts
  src/app/compnents/menjacnica/exchange/exchange.component.ts
  src/app/compnents/password_components/password-activation/password-activation.component.ts
  src/app/compnents/password_components/reset-password/password-confirmation/password-confirmation.component.ts
  src/app/compnents/password_components/reset-password/reset-password.component.ts
  src/app/compnents/transaction_components/paying/paying.component.html
  src/app/compnents/transaction_components/paying/paying.component.ts
  src/app/services/account.service.ts
Labels: size/L, approved, lgtm

#120 Sprint 6 Finish
  .prow/build.yaml
  .prow/frontend.yaml
  OWNERS
  cypress/e2e/admin-login.cy.ts
  cypress/e2e/create-employee.cy.ts
  cypress/e2e/create-user.cy.ts
  cypress/e2e/transaction.cy.ts
  cypress/e2e/user-login.cy.ts
  src/app/compnents/credit_components/credit-list/credit-list.component.html
  src/app/compnents/credit_components/credit-transaction/credit-transaction.component.ts
  src/app/compnents/employee_components/user-add-account-form/user-add-account-form.component.ts
  src/app/compnents/login/admin-login/admin-login.component.ts
  src/app/compnents/login/company-login/company-login.component.ts
  src/app/compnents/login/userlogin/userlogin.component.ts
  src/app/compnents/menjacnica/exchange/exchange.component.ts
  src/app/compnents/password_components/password-activation/password-activation.component.ts
  src/app/compnents/password_components/reset-password/password-confirmation/password-confirmation.component.ts
  src/app/compnents/password_components/reset-password/reset-password.component.ts
  src/app/compnents/transaction_components/paying/paying.component.html
  src/app/compnents/transaction_components/paying/paying.component.ts
  src/app/services/account.service.ts
Labels: size/L, approved, lgtm
