Repository RAF-SI-2023/Banka-3-Frontend, pull requests merged in 2024-07, with the labels that each got.

#198 sitne izmene 2
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/profit-table/profit-table.component.ts
  src/app/services/account.service.ts
Labels: size/S, approved, lgtm

#200 uplata i isplata marznih racuna
  src/app/app.module.ts
  src/app/compnents/add-withdraw-margin-account/add-withdraw-margin-account.component.css
  src/app/compnents/add-withdraw-margin-account/add-withdraw-margin-account.component.html
  src/app/compnents/add-withdraw-margin-account/add-withdraw-margin-account.component.spec.ts
  src/app/compnents/add-withdraw-margin-account/add-withdraw-margin-account.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.css
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.css
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/options/options.component.css
  src/app/compnents/login/admin-login/admin-login.component.css
  src/app/compnents/login/company-login/company-login.component.css
  src/app/compnents/login/userlogin/userlogin.component.css
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.css
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.html
  src/app/compnents/margin-account/margin-account-view/margin-account-view.component.ts
  src/app/compnents/otc/bank-otc/bank-otc.component.css
  src/app/compnents/otc/bank-otc/bank-otc.component.html
  src/app/compnents/otc/bank-otc/bank-otc.component.ts
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
Labels: size/L, approved, lgtm

#201 E2E Testovi za podizanje kredita i za menjacnicu, stock i profit banke
  cypress/e2e/exchange-and-stock.cy.ts
  cypress/e2e/loan-request.cy.ts
Labels: size/L, approved, lgtm

#202 ogisa final
  cypress/e2e/admin-login.cy.ts
  cypress/e2e/agent-supervisor.cy.ts
  cypress/e2e/buy-stock-and-future.cy.ts
  cypress/e2e/create-employee.cy.ts
  cypress/e2e/create-user.cy.ts
  cypress/e2e/exchange-and-stock.cy.ts
  cypress/e2e/loan-request.cy.ts
  cypress/e2e/otc-agent-approves.cy.ts
  cypress/e2e/transaction.cy.ts
  cypress/e2e/user-login.cy.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/otc/bank-otc/bank-otc.component.css
  src/app/compnents/otc/bank-otc/bank-otc.component.html
  src/app/compnents/otc/otc-company-view/otc-company-view.component.css
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.html
  src/app/compnents/profit-table/profit-table.component.html
  src/app/compnents/transaction_components/paying/paying.component.html
  src/app/compnents/transaction_components/paying/paying.component.ts
Labels: approved, size/XXL, lgtm

#204 Update README.md
  README.md
Labels: approved, size/XS, lgtm
