Repository RAF-SI-2023/Banka-3-Frontend, pull requests merged in 2024-05, with the labels that each got.

#124 FRN-35 Povezivanje bankomanta sa backendom
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.css
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.html
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.ts
  src/app/compnents/card_components/card-view/card-view.component.ts
  src/app/compnents/navbar/navbar.component.html
Labels: size/L, approved, lgtm

#129 FRN-37 Izlistavanje transakcija za kompanije
  README.md
  package-lock.json
  package.json
  src/app/compnents/company-home-page/company-home-page.component.html
  src/app/compnents/company-home-page/company-home-page.component.ts
  src/app/compnents/home-page/home-page.component.ts
  src/app/services/user.service.ts
Labels: approved, lgtm

#130 Odradjen Issue
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/services/exchange.service.ts
Labels: size/M, approved, lgtm

#131 Sprint 6 refactor
  README.md
  package-lock.json
  package.json
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.css
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.html
  src/app/compnents/card_components/bankomat-view/bankomat-view.component.ts
  src/app/compnents/card_components/card-view/card-view.component.ts
  src/app/compnents/company-home-page/company-home-page.component.html
  src/app/compnents/company-home-page/company-home-page.component.ts
  src/app/compnents/home-page/home-page.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/services/exchange.service.ts
  src/app/services/user.service.ts
Labels: size/XL, approved, lgtm

#132 Configure/environment files
  .prow/build.yaml
  angular.json
  package.json
  src/app/services/account.service.ts
  src/app/services/exchange.service.ts
  src/app/services/user.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/M, approved, lgtm

#133 FRN-40 sa mock podacima
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.css
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.spec.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-view/otc-view.component.css
  src/app/compnents/otc/otc-view/otc-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.spec.ts
  src/app/compnents/otc/otc-view/otc-view.component.ts
Labels: size/XL, approved, lgtm

#134 OTC za korisnika i stavljanje private/public akcija
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/sell-hartije/sell-hartije.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.css
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.spec.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/navbar/navbar.component.html
Labels: approved, lgtm

#136 Sprint 7 berza
  src/app/app-routing.module.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/login/userlogin/userlogin.component.ts
  src/app/compnents/navbar/navbar.component.ts
  src/app/guards/company.guard.ts
  src/app/models/models.ts
Labels: size/M, approved, lgtm

#137 Web socketi
  src/app/compnents/listing_components/buy-hartije-popup/buy-hartije-popup.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/options/options.component.ts
  src/app/services/websocket.service.spec.ts
  src/app/services/websocket.service.ts
Labels: size/L, approved, lgtm

#138 Frn 41 supervisor view update
  src/app/models/models.ts
  src/app/services/account.service.ts
Labels: size/M, approved, lgtm

#139 Sprint 7 merge
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/listing_components/buy-hartije-popup/buy-hartije-popup.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.html
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.html
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/options/options.component.ts
  src/app/compnents/listing_components/sell-hartije/sell-hartije.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.css
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.html
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.spec.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/login/userlogin/userlogin.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.css
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.html
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.spec.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-view/otc-view.component.css
  src/app/compnents/otc/otc-view/otc-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.spec.ts
  src/app/compnents/otc/otc-view/otc-view.component.ts
  src/app/guards/company.guard.ts
  src/app/models/models.ts
  src/app/services/account.service.ts
  src/app/services/websocket.service.spec.ts
  src/app/services/websocket.service.ts
Labels: approved, size/XXL, lgtm

#141 Increase build budget
  angular.json
Labels: approved, size/XS, lgtm

#144 OTC za korisnika i stavljanje private/public akcija (#134)
  src/app/app-routing.module.ts
Labels: approved, size/XS, lgtm

#145 FRN-39 [OTC za pravna lica]
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.css
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.html
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.spec.ts
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.css
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-company-view/otc-company-view.component.spec.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.ts
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.css
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.html
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.spec.ts
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
Labels: size/XL, approved, lgtm

#147 Sprint 7 merge?
  angular.json
Labels: approved, size/XS, lgtm

#149 Sprint 7 final
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.css
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.html
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.spec.ts
  src/app/compnents/otc/otc-company-buy-popup/otc-company-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.css
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-company-view/otc-company-view.component.spec.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.ts
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.css
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.html
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.spec.ts
  src/app/compnents/otc/otc-decline-popup/otc-decline-popup.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
Labels: size/XL, approved, lgtm

#150 OTC uradjen
  src/app/app.module.ts
  src/app/compnents/listing_components/buy-hartije-popup/buy-hartije-popup.component.ts
  src/app/compnents/listing_components/buy-hartije/buy-hartije.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.css
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.html
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.spec.ts
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.css
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-company-view/otc-company-view.component.ts
  src/app/compnents/otc/otc-view/otc-view.component.css
  src/app/compnents/otc/otc-view/otc-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/user.service.ts
Labels: approved, size/XXL, lgtm

#156 Sitnice za OTC
  src/app/compnents/home-page/home-page.component.html
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
Labels: size/M, approved, lgtm

#157 Sprint 7 refactor merge
  src/app/app.module.ts
  src/app/compnents/home-page/home-page.component.html
  src/app/compnents/listing_components/buy-hartije-popup/buy-hartije-popup.component.ts
  src/app/compnents/listing_components/buy-hartije/buy-hartije.component.ts
  src/app/compnents/listing_components/listing-list/listing-list.component.ts
  src/app/compnents/listing_components/my-stocks/my-stocks.component.ts
  src/app/compnents/listing_components/set-stock-visibility/set-stock-visibility.component.ts
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.css
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.html
  src/app/compnents/listing_components/supervisor-listsing-list/supervisor-listsing-list.component.ts
  src/app/compnents/navbar/navbar.component.html
  src/app/compnents/navbar/navbar.component.ts
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.css
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.html
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.spec.ts
  src/app/compnents/otc/otc-accept-decline/otc-accept-decline.component.ts
  src/app/compnents/otc/otc-buy-popup/otc-buy-popup.component.ts
  src/app/compnents/otc/otc-company-view/otc-company-view.component.css
  src/app/compnents/otc/otc-company-view/otc-company-view.component.html
  src/app/compnents/otc/otc-company-view/otc-company-view.component.ts
  src/app/compnents/otc/otc-view/otc-view.component.css
  src/app/compnents/otc/otc-view/otc-view.component.html
  src/app/compnents/otc/otc-view/otc-view.component.ts
  src/app/models/models.ts
  src/app/services/exchange.service.ts
  src/app/services/user.service.ts
Labels: approved, lgtm
